version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - uploads:/app/uploads
    depends_on:
      - minio
  minio:
    image: minio/minio:latest
    command: server /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"

volumes:
  uploads:
